// <auto-generated />
using System;
using Backend.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Backend.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260624200444_AddExamGradeEntry")]
    partial class AddExamGradeEntry
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Backend.Models.AssessmentComponent", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CourseId")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("Date")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("Weight")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.HasIndex("CourseId");

                    b.ToTable("AssessmentComponents");
                });

            modelBuilder.Entity("Backend.Models.Course", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Akts")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("ApprovedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("ClassYear")
                        .HasColumnType("integer");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("ContentStatus")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<string>("CourseType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<int>("Credit")
                        .HasColumnType("integer");

                    b.Property<string>("Department")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Description")
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)");

                    b.Property<int?>("InstructorId")
                        .HasColumnType("integer");

                    b.Property<bool>("IsLocked")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsMandatory")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Objective")
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)");

                    b.Property<string>("ReviewNote")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<int?>("ReviewedByUserId")
                        .HasColumnType("integer");

                    b.Property<string>("Semester")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<DateTime?>("SubmittedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("WeeklyHours")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("InstructorId");

                    b.HasIndex("ReviewedByUserId");

                    b.ToTable("Courses");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Akts = 6,
                            ClassYear = 1,
                            Code = "BIL101",
                            ContentStatus = "Draft",
                            CourseType = "Teorik+Lab",
                            Credit = 4,
                            Department = "Bilgisayar Mühendisliği",
                            InstructorId = 2,
                            IsLocked = false,
                            IsMandatory = true,
                            Name = "Programlamaya Giriş",
                            Semester = "2024-Güz",
                            WeeklyHours = 4
                        },
                        new
                        {
                            Id = 2,
                            Akts = 5,
                            ClassYear = 2,
                            Code = "BIL202",
                            ContentStatus = "Draft",
                            CourseType = "Teorik",
                            Credit = 3,
                            Department = "Bilgisayar Mühendisliği",
                            InstructorId = 2,
                            IsLocked = false,
                            IsMandatory = true,
                            Name = "Veri Yapıları",
                            Semester = "2024-Güz",
                            WeeklyHours = 3
                        });
                });

            modelBuilder.Entity("Backend.Models.CourseSurveyQuestion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CourseId")
                        .HasColumnType("integer");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<int?>("LearningOutcomeId")
                        .HasColumnType("integer");

                    b.Property<string>("QuestionText")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("CourseId");

                    b.HasIndex("LearningOutcomeId");

                    b.ToTable("CourseSurveyQuestions");
                });

            modelBuilder.Entity("Backend.Models.CourseTopic", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CourseId")
                        .HasColumnType("integer");

                    b.Property<string>("Description")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<int>("OrderNumber")
                        .HasColumnType("integer");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.HasKey("Id");

                    b.HasIndex("CourseId");

                    b.ToTable("CourseTopics");
                });

            modelBuilder.Entity("Backend.Models.Enrollment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CourseId")
                        .HasColumnType("integer");

                    b.Property<decimal?>("Final")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("MakeUp")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("Midterm")
                        .HasColumnType("numeric");

                    b.Property<int>("StudentId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("CourseId");

                    b.HasIndex("StudentId", "CourseId")
                        .IsUnique();

                    b.ToTable("Enrollments");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CourseId = 1,
                            Final = 80m,
                            Midterm = 70m,
                            StudentId = 1
                        },
                        new
                        {
                            Id = 2,
                            CourseId = 1,
                            Final = 55m,
                            MakeUp = 65m,
                            Midterm = 60m,
                            StudentId = 2
                        },
                        new
                        {
                            Id = 3,
                            CourseId = 1,
                            StudentId = 3
                        },
                        new
                        {
                            Id = 4,
                            CourseId = 2,
                            Final = 85m,
                            Midterm = 90m,
                            StudentId = 1
                        });
                });

            modelBuilder.Entity("Backend.Models.Exam", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CourseId")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("Date")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("ExamMethod")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ExamType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("QuestionCount")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("CourseId");

                    b.ToTable("Exams");
                });

            modelBuilder.Entity("Backend.Models.ExamQuestion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("BookletAQuestionNumber")
                        .HasColumnType("integer");

                    b.Property<int?>("BookletBQuestionNumber")
                        .HasColumnType("integer");

                    b.Property<int?>("BookletCQuestionNumber")
                        .HasColumnType("integer");

                    b.Property<int?>("BookletDQuestionNumber")
                        .HasColumnType("integer");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Difficulty")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("ExamId")
                        .HasColumnType("integer");

                    b.Property<int>("QuestionNumber")
                        .HasColumnType("integer");

                    b.Property<decimal>("Score")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.HasIndex("ExamId");

                    b.ToTable("ExamQuestions");
                });

            modelBuilder.Entity("Backend.Models.ExamQuestionLearningOutcome", b =>
                {
                    b.Property<int>("ExamQuestionId")
                        .HasColumnType("integer");

                    b.Property<int>("LearningOutcomeId")
                        .HasColumnType("integer");

                    b.HasKey("ExamQuestionId", "LearningOutcomeId");

                    b.HasIndex("LearningOutcomeId");

                    b.ToTable("ExamQuestionLearningOutcomes");
                });

            modelBuilder.Entity("Backend.Models.ExamQuestionStudentScore", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("ExamQuestionId")
                        .HasColumnType("integer");

                    b.Property<int>("ExamStudentGradeId")
                        .HasColumnType("integer");

                    b.Property<decimal>("Score")
                        .HasColumnType("numeric");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("ExamQuestionId");

                    b.HasIndex("ExamStudentGradeId", "ExamQuestionId")
                        .IsUnique();

                    b.ToTable("ExamQuestionStudentScores");
                });

            modelBuilder.Entity("Backend.Models.ExamStudentGrade", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("ExamId")
                        .HasColumnType("integer");

                    b.Property<bool>("IsCompleted")
                        .HasColumnType("boolean");

                    b.Property<int>("StudentId")
                        .HasColumnType("integer");

                    b.Property<decimal>("TotalScore")
                        .HasColumnType("numeric");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("StudentId");

                    b.HasIndex("ExamId", "StudentId")
                        .IsUnique();

                    b.ToTable("ExamStudentGrades");
                });

            modelBuilder.Entity("Backend.Models.LOPOMapping", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("ContributionLevel")
                        .HasColumnType("integer");

                    b.Property<int>("LearningOutcomeId")
                        .HasColumnType("integer");

                    b.Property<int>("ProgramOutcomeId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ProgramOutcomeId");

                    b.HasIndex("LearningOutcomeId", "ProgramOutcomeId")
                        .IsUnique();

                    b.ToTable("LOPOMappings");
                });

            modelBuilder.Entity("Backend.Models.LearningOutcome", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("BloomLevel")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("Component")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("CourseId")
                        .HasColumnType("integer");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.HasKey("Id");

                    b.HasIndex("CourseId");

                    b.ToTable("LearningOutcomes");
                });

            modelBuilder.Entity("Backend.Models.ProgramOutcome", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Details")
                        .HasColumnType("text");

                    b.Property<int?>("GroupId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("GroupId");

                    b.ToTable("ProgramOutcomes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Code = "PÇ1",
                            Description = "Matematik, fen bilimleri ve bilgisayar mühendisliği konularında yeterli bilgi birikimi",
                            GroupId = 1
                        },
                        new
                        {
                            Id = 2,
                            Code = "PÇ2",
                            Description = "Bilgisayar mühendisliği problemlerini saptama, tanımlama, formüle etme ve çözme becerisi",
                            GroupId = 1
                        },
                        new
                        {
                            Id = 3,
                            Code = "PÇ3",
                            Description = "Karmaşık sistemleri, süreçleri veya ürünleri tasarlama becerisi",
                            GroupId = 1
                        },
                        new
                        {
                            Id = 4,
                            Code = "PÇ4",
                            Description = "Karmaşık mühendislik problemlerini araştırma becerisi",
                            GroupId = 1
                        },
                        new
                        {
                            Id = 5,
                            Code = "PÇ5",
                            Description = "Modern araç ve teknikleri kullanma becerisi",
                            GroupId = 1
                        },
                        new
                        {
                            Id = 6,
                            Code = "PÇ6",
                            Description = "Mühendislik uygulamalarının toplumsal ve küresel boyutlarını anlama",
                            GroupId = 2
                        },
                        new
                        {
                            Id = 7,
                            Code = "PÇ7",
                            Description = "Mesleki ve etik sorumluluk bilinci",
                            GroupId = 2
                        },
                        new
                        {
                            Id = 8,
                            Code = "PÇ8",
                            Description = "Etkin iletişim kurma becerisi",
                            GroupId = 2
                        },
                        new
                        {
                            Id = 9,
                            Code = "PÇ9",
                            Description = "Yaşam boyu öğrenmenin gerekliliği bilinci",
                            GroupId = 2
                        },
                        new
                        {
                            Id = 10,
                            Code = "PÇ10",
                            Description = "Proje yönetimi, risk yönetimi ve değişiklik yönetimi becerisi",
                            GroupId = 2
                        });
                });

            modelBuilder.Entity("Backend.Models.ProgramOutcomeGroup", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("ProgramOutcomeGroups");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Code = "GRP1",
                            Name = "Teknik Yeterlilikler"
                        },
                        new
                        {
                            Id = 2,
                            Code = "GRP2",
                            Name = "Mesleki ve Etik Sorumluluklar"
                        });
                });

            modelBuilder.Entity("Backend.Models.Student", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .HasColumnType("text");

                    b.Property<DateTime>("EnrollmentDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("StudentNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Students");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Email = "ahmet.yilmaz@ogr.edu.tr",
                            EnrollmentDate = new DateTime(2021, 9, 15, 0, 0, 0, 0, DateTimeKind.Utc),
                            FirstName = "Ahmet",
                            IsActive = true,
                            LastName = "Yılmaz",
                            StudentNumber = "2021001"
                        },
                        new
                        {
                            Id = 2,
                            Email = "ayse.kaya@ogr.edu.tr",
                            EnrollmentDate = new DateTime(2021, 9, 15, 0, 0, 0, 0, DateTimeKind.Utc),
                            FirstName = "Ayşe",
                            IsActive = true,
                            LastName = "Kaya",
                            StudentNumber = "2021002"
                        },
                        new
                        {
                            Id = 3,
                            Email = "mehmet.demir@ogr.edu.tr",
                            EnrollmentDate = new DateTime(2022, 9, 12, 0, 0, 0, 0, DateTimeKind.Utc),
                            FirstName = "Mehmet",
                            IsActive = true,
                            LastName = "Demir",
                            StudentNumber = "2022015"
                        });
                });

            modelBuilder.Entity("Backend.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Email = "admin@mudek.edu.tr",
                            FullName = "Sistem Yöneticisi",
                            PasswordHash = "$2a$11$nKSgs23VvGfIptin60wqB.z/b7RyNWK8ixzrKy6gd4fAPc2ON1bee",
                            Role = "Admin"
                        },
                        new
                        {
                            Id = 2,
                            Email = "ali.vural@mudek.edu.tr",
                            FullName = "Dr. Ali Vural",
                            PasswordHash = "$2a$11$McaBkQ1M1QZPn7fl3OzYS.PpxfDWLJgRx2x2ZBcfq6WzhtTsqHB1S",
                            Role = "Instructor"
                        });
                });

            modelBuilder.Entity("Backend.Models.AssessmentComponent", b =>
                {
                    b.HasOne("Backend.Models.Course", "Course")
                        .WithMany("AssessmentComponents")
                        .HasForeignKey("CourseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Course");
                });

            modelBuilder.Entity("Backend.Models.Course", b =>
                {
                    b.HasOne("Backend.Models.User", "Instructor")
                        .WithMany("Courses")
                        .HasForeignKey("InstructorId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Backend.Models.User", "ReviewedBy")
                        .WithMany()
                        .HasForeignKey("ReviewedByUserId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Instructor");

                    b.Navigation("ReviewedBy");
                });

            modelBuilder.Entity("Backend.Models.CourseSurveyQuestion", b =>
                {
                    b.HasOne("Backend.Models.Course", "Course")
                        .WithMany("SurveyQuestions")
                        .HasForeignKey("CourseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Backend.Models.LearningOutcome", "LearningOutcome")
                        .WithMany()
                        .HasForeignKey("LearningOutcomeId");

                    b.Navigation("Course");

                    b.Navigation("LearningOutcome");
                });

            modelBuilder.Entity("Backend.Models.CourseTopic", b =>
                {
                    b.HasOne("Backend.Models.Course", "Course")
                        .WithMany("CourseTopics")
                        .HasForeignKey("CourseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Course");
                });

            modelBuilder.Entity("Backend.Models.Enrollment", b =>
                {
                    b.HasOne("Backend.Models.Course", "Course")
                        .WithMany("Enrollments")
                        .HasForeignKey("CourseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Backend.Models.Student", "Student")
                        .WithMany("Enrollments")
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Course");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("Backend.Models.Exam", b =>
                {
                    b.HasOne("Backend.Models.Course", "Course")
                        .WithMany("Exams")
                        .HasForeignKey("CourseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Course");
                });

            modelBuilder.Entity("Backend.Models.ExamQuestion", b =>
                {
                    b.HasOne("Backend.Models.Exam", "Exam")
                        .WithMany("Questions")
                        .HasForeignKey("ExamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Exam");
                });

            modelBuilder.Entity("Backend.Models.ExamQuestionLearningOutcome", b =>
                {
                    b.HasOne("Backend.Models.ExamQuestion", "ExamQuestion")
                        .WithMany("LearningOutcomeMappings")
                        .HasForeignKey("ExamQuestionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Backend.Models.LearningOutcome", "LearningOutcome")
                        .WithMany("ExamQuestionMappings")
                        .HasForeignKey("LearningOutcomeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ExamQuestion");

                    b.Navigation("LearningOutcome");
                });

            modelBuilder.Entity("Backend.Models.ExamQuestionStudentScore", b =>
                {
                    b.HasOne("Backend.Models.ExamQuestion", "ExamQuestion")
                        .WithMany()
                        .HasForeignKey("ExamQuestionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Backend.Models.ExamStudentGrade", "ExamStudentGrade")
                        .WithMany("QuestionScores")
                        .HasForeignKey("ExamStudentGradeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ExamQuestion");

                    b.Navigation("ExamStudentGrade");
                });

            modelBuilder.Entity("Backend.Models.ExamStudentGrade", b =>
                {
                    b.HasOne("Backend.Models.Exam", "Exam")
                        .WithMany()
                        .HasForeignKey("ExamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Backend.Models.Student", "Student")
                        .WithMany()
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Exam");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("Backend.Models.LOPOMapping", b =>
                {
                    b.HasOne("Backend.Models.LearningOutcome", "LearningOutcome")
                        .WithMany("LOPOMappings")
                        .HasForeignKey("LearningOutcomeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Backend.Models.ProgramOutcome", "ProgramOutcome")
                        .WithMany("LOPOMappings")
                        .HasForeignKey("ProgramOutcomeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("LearningOutcome");

                    b.Navigation("ProgramOutcome");
                });

            modelBuilder.Entity("Backend.Models.LearningOutcome", b =>
                {
                    b.HasOne("Backend.Models.Course", "Course")
                        .WithMany("LearningOutcomes")
                        .HasForeignKey("CourseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Course");
                });

            modelBuilder.Entity("Backend.Models.ProgramOutcome", b =>
                {
                    b.HasOne("Backend.Models.ProgramOutcomeGroup", "Group")
                        .WithMany("ProgramOutcomes")
                        .HasForeignKey("GroupId");

                    b.Navigation("Group");
                });

            modelBuilder.Entity("Backend.Models.Course", b =>
                {
                    b.Navigation("AssessmentComponents");

                    b.Navigation("CourseTopics");

                    b.Navigation("Enrollments");

                    b.Navigation("Exams");

                    b.Navigation("LearningOutcomes");

                    b.Navigation("SurveyQuestions");
                });

            modelBuilder.Entity("Backend.Models.Exam", b =>
                {
                    b.Navigation("Questions");
                });

            modelBuilder.Entity("Backend.Models.ExamQuestion", b =>
                {
                    b.Navigation("LearningOutcomeMappings");
                });

            modelBuilder.Entity("Backend.Models.ExamStudentGrade", b =>
                {
                    b.Navigation("QuestionScores");
                });

            modelBuilder.Entity("Backend.Models.LearningOutcome", b =>
                {
                    b.Navigation("ExamQuestionMappings");

                    b.Navigation("LOPOMappings");
                });

            modelBuilder.Entity("Backend.Models.ProgramOutcome", b =>
                {
                    b.Navigation("LOPOMappings");
                });

            modelBuilder.Entity("Backend.Models.ProgramOutcomeGroup", b =>
                {
                    b.Navigation("ProgramOutcomes");
                });

            modelBuilder.Entity("Backend.Models.Student", b =>
                {
                    b.Navigation("Enrollments");
                });

            modelBuilder.Entity("Backend.Models.User", b =>
                {
                    b.Navigation("Courses");
                });
#pragma warning restore 612, 618
        }
    }
}
